---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: master
    service: ${GIT_REPO}    
  triggers:
  - type: commit
  jobs:
  - name: Build image
    type: builder
    build_type: cr
    target:
      region_id: ${REGISTRY_REGION_ID}
      namespace: ${REGISTRY_NAMESPACE}
      api_key: ${API_KEY}
    image_name: ${CF_APP_NAME}
    COMMAND: |
      #!/bin/bash
      source ./scripts/build.sh
- name: VALIDATE
  inputs:
  - type: job
    stage: BUILD
    job: Build image
  triggers:
  - type: stage
  properties:
  - name: FULL_REPOSITORY_NAME
    value: ''
    type: text  
  jobs:
  - name: Vulnerability Advisor
    type: tester
    extension_id: ibm.devops.services.pipeline.crawler.tester
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
    WAIT_TIME: '5'
- name: DEPLOY
  inputs:
  - type: job
    stage: BUILD
    job: Build image
  triggers:
  - type: stage
  properties:
  - name: buildprops
    value: build.properties
    type: file
  - name: CLUSTER_NAMESPACE
    value: ${PROD_CLUSTER_NAMESPACE}
    type: text  
  jobs:
  - name: Deploy Helm Chart
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      api_key: ${API_KEY}
      kubernetes_cluster: ${PROD_CLUSTER_NAME}
    script: |
      #!/bin/bash
      source ./scripts/deploy.sh